services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=sibsutisgo'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
