spring:
  application:
    name: SibsutisGO

  datasource:
    url: jdbc:postgresql://localhost:5433/sibsutisgo
    username: postgres
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update

    docker:
    compose:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
        concurrency: 1
        max-concurrency: 5

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

application:
  security:
    jwt:
      secret-key: "SANCHEZKSESHHHHiiiiiSTEPAAANIDZELONGENOUGHKEY12345"
      expiration: 86400000
      refresh-token:
        expiration: 604800000
